# Generated by Django 2.2 on 2019-11-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFellow',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('姓名', models.CharField(max_length=30)),
                ('性别', models.BooleanField()),
                ('联系方式', models.CharField(max_length=11)),
                ('电子邮箱', models.EmailField(max_length=254)),
                ('院系', models.CharField(max_length=100)),
                ('班级', models.CharField(max_length=30, null=True)),
                ('学历', models.CharField(default='本科学生', max_length=50)),
                ('学制', models.IntegerField(null=True)),
                ('入学年份', models.DateField()),
                ('毕业年份', models.DateField()),
                ('辅导员老师或印象最深刻的任课老师', models.CharField(max_length=40, null=True)),
                ('现工作单位', models.CharField(max_length=100)),
                ('工作单位地址', models.CharField(max_length=200, null=True)),
                ('行业类别', models.CharField(max_length=20, null=True)),
                ('单位性质', models.CharField(max_length=30, null=True)),
                ('现职务职称', models.CharField(max_length=100, null=True)),
                ('所获荣誉', models.TextField(null=True)),
                ('备注', models.TextField(null=True)),
            ],
        ),
    ]
