# Generated by Django 2.2 on 2019-12-01 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0002_auto_20191201_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='information',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='home.SchoolFellow'),
        ),
    ]
