# Generated by Django 2.2 on 2019-12-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0003_auto_20191201_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfellow',
            name='性别',
            field=models.CharField(default='男', max_length=1),
        ),
    ]
